name: Recipe to PDF
on:
  push:
    branches:
      - main
    paths:
      - 'Recipe Book/**/**.md'
      - '.resources/RecipeTemplate.md'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.set-output.outputs.files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git fetch --prune --unshallow

      - name: Get last run timestamp
        id: get_last_run
        run: |
          last_run=$(cat /github/workspace/.last_run_timestamp 2>/dev/null || echo "1970-01-01T00:00:00Z")
          echo "LAST_RUN=$last_run" >> $GITHUB_ENV

      - name: Save current timestamp
        run: |
          date -u +"%Y-%m-%dT%H:%M:%SZ" > /github/workspace/.last_run_timestamp

      - name: Find modified Markdown files
        id: find_files
        run: |
          files=$(git diff --name-only --since="${LAST_RUN}" | grep '^Recipe Book/.*\.md$' || true)
          echo "Changed files: $files"
          echo "::set-output name=files::${files}"

  build-pdf:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.detect-changes.outputs.files) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Convert Markdown to PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: ${{ matrix.file }}
          output_dir: Recipe Book/PDF Recipe Archives
          images_dir: .resources/images
          image_import: ./.resources/images
          build_html: false
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.file }}
          path: Recipe Book/PDF Recipe Archive